# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48d695359780d1cdb9b93d4229730043999ec73a3066dee3681178ceb56f807bb9a4199621deb617d108a3f1d2abaf7c693a8e41357025388d23f62708855bf5

test:
  secret_key_base: 02f36ab5c11758f9a1a8c1c0ca628d3339a3ccdbeaabf224abb5e2e02a6ca3cbd7a5222c617b10bebb90c8495cd51ebc527cfb73a2861d885e9863502df06a9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
